name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or another branch you are using for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install  # or yarn install, depending on your project
      - run: npm run build  # or the command that builds your static files
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this based on your output directory
